from turtle import *
from time import sleep
t =  Turtle()
t.speed(0)

#bamdeira holanda

def Bandeira0():
     t.pu()
     t.goto(0, 0)
     t.pd()
     t.fillcolor('blue')
     t.begin_fill()
     for _ in range(2):
        t.lt(90)
        t.fd(100)
        t.lt(90)
        t.fd(400)
     t.end_fill()
     t.fillcolor('white')
     t.begin_fill()
     t.lt(90)
     t.fd(200)
     t.lt(90)
     t.fd(400)
     t.lt(90)
     t.fd(100)
     t.lt(90)
     t.fd(400)
     t.end_fill()
     t.fillcolor('red')
     t.begin_fill()
     t.lt(90)
     t.fd(200)
     t.lt(90)
     t.fd(400)
     t.lt(90)
     t.fd(100)
     t.lt(90)
     t.fd(400)
     t.end_fill()
     sleep(5)
     t.clear()

#bandeira Russia

def BandeiraR():
     t.pu()
     t.goto(0, 0)
     t.pd()
     t.fillcolor('red')
     t.begin_fill()
     for _ in range(2):
        t.lt(90)
        t.fd(100)
        t.lt(90)
        t.fd(400)
     t.end_fill()
     t.fillcolor('white')
     t.begin_fill()
     t.lt(90)
     t.fd(200)
     t.lt(90)
     t.fd(400)
     t.lt(90)
     t.fd(100)
     t.lt(90)
     t.fd(400)
     t.end_fill()
     t.fillcolor('blue')
     t.begin_fill()
     t.lt(90)
     t.fd(200)
     t.lt(90)
     t.fd(400)
     t.lt(90)
     t.fd(100)
     t.lt(90)
     t.fd(400)
     t.end_fill()
     sleep(5)
     t.clear()


#bandeira alemanha

def Bandeira1():
    t.pu()
    t.goto(0, 0)
    t.pd()
    t.fillcolor('black')
    t.begin_fill()
    for _ in range(2):
        t.lt(90)
        t.fd(100)
        t.lt(90)
        t.fd(400)
    t.end_fill()
    t.fillcolor('red')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    t.fillcolor('yellow')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    sleep(5)
    t.clear()

#bandeira gabao

def Bandeira2():
    t.pu()
    t.goto(0, 0)
    t.pd()
    t.fillcolor('green')
    t.begin_fill()
    for _ in range(2):
        t.lt(90)
        t.fd(100)
        t.lt(90)
        t.fd(400)
    t.end_fill()
    t.fillcolor('yellow')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    t.fillcolor('blue')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    sleep(5)
    t.clear()

# bandeira iemen

    def Bandeira2():
     t.pu()
    t.goto(0, 0)
    t.pd()
    t.fillcolor('red')
    t.begin_fill()
    for _ in range(2):
        t.lt(90)
        t.fd(100)
        t.lt(90)
        t.fd(400)
    t.end_fill()
    t.fillcolor('white')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    t.fillcolor('black')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    sleep(5)
    t.clear()
    Bandeira2()






#bandeira Áustria
def Bandeira3():
    t.pu()
    t.goto(0, 0)
    t.pd()
    t.fillcolor('red')
    t.begin_fill()
    for _ in range(2):
        t.lt(90)
        t.fd(100)
        t.lt(90)
        t.fd(400)
    t.end_fill()
    t.fillcolor('white')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    t.fillcolor('red')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    sleep(5)
    t.clear()

#bandeira colombia
 
def Bandeira4():
    t.pu()
    t.goto(0, 0)
    t.pd()
    t.fillcolor('red')
    t.begin_fill()
    for _ in range(2):
        t.lt(90)
        t.fd(75)
        t.lt(90)
        t.fd(400)
    t.end_fill()
    t.fillcolor('blue')
    t.begin_fill()
    t.lt(90)
    t.fd(150)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(75)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    t.fillcolor('yellow')
    t.begin_fill()
    t.lt(90)
    t.fd(225)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(150)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    sleep(5)
    t.clear()

#bandeira hungria

def Bandeira5():
    t.pu()
    t.goto(0, 0)
    t.pd()
    t.fillcolor('green')
    t.begin_fill()
    for _ in range(2):
        t.lt(90)
        t.fd(100)
        t.lt(90)
        t.fd(400)
    t.end_fill()
    t.fillcolor('white')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    t.fillcolor('red')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    sleep(5)
    t.clear()


def Bandeira6():
    t.pu()
    t.goto(0, 0)
    t.pd()
    t.fillcolor('green')
    t.begin_fill()
    for _ in range(2):
        t.lt(90)
        t.fd(100)
        t.lt(90)
        t.fd(400)
    t.end_fill()
    t.fillcolor('white')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    t.fillcolor('red')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    t.lt(180)
    t.fd(400)
    t.rt(90)
    t.fd(100)
    t.fillcolor('black')
    t.begin_fill()
    t.rt(135)
    t.fd(140)
    t.rt(45)
    t.fd(100)
    t.rt(45)
    t.fd(140)
    t.rt(135)
    t.fd(300)
    t.end_fill()
    sleep(5)
    t.clear()

def Bandeira7():
    t.pu()
    t.setheading(0)
    t.goto(0, 0)
    t.pd()
    t.fillcolor('black')
    t.begin_fill()
    for _ in range(2):
        t.lt(90)
        t.fd(100)
        t.lt(90)
        t.fd(400)
    t.end_fill()
    t.fillcolor('white')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    t.fillcolor('green')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    t.lt(180)
    t.fd(400)
    t.rt(90)
    t.fd(100)
    t.fillcolor('red')
    t.begin_fill()
    t.rt(135)
    t.fd(212)
    t.rt(90)
    t.fd(212)
    t.lt(90)
    t.end_fill()
    sleep(5)
    t.clear()

def Bandeira7():
    t.pu()
    t.setheading(0)
    t.goto(0, 0)
    t.pd()
    t.fillcolor('green')
    t.begin_fill()
    for _ in range(2):
        t.lt(90)
        t.fd(100)
        t.lt(90)
        t.fd(400)
    t.end_fill()
    t.fillcolor('white')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    t.fillcolor('black')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(300)
    t.lt(90)
    t.fillcolor('red')
    t.begin_fill()
    t.fd(300)
    t.rt(90)
    t.fd(100)
    t.rt(90)
    t.fd(300)
    t.rt(90)
    t.fd(100)
    t.end_fill()
    sleep(5)
    t.clear()

def Bandeira8():
    t.pu()
    t.setheading(0)
    t.goto(0, 0)
    t.pd()
    t.fillcolor('green')
    t.begin_fill()
    for _ in range(2):
        t.lt(90)
        t.fd(100)
        t.lt(90)
        t.fd(400)
    t.end_fill()
    t.fillcolor('white')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    t.fillcolor('black')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    t.lt(180)
    t.fd(400)
    t.rt(90)
    t.fd(100)
    t.fillcolor('red')
    t.begin_fill()
    t.rt(135)
    t.fd(212)
    t.rt(90)
    t.fd(212)
    t.lt(90)
    t.end_fill()
    sleep(5)
    t.clear()


#bandeira níger

def Bandeira9():
    t.pu()
    t.setheading(0)
    t.goto(0, 0)
    t.pd()
    t.fillcolor('orange')
    t.begin_fill()
    for _ in range(2):
        t.lt(90)
        t.fd(100)
        t.lt(90)
        t.fd(400)
    t.end_fill()
    t.fillcolor('white')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    t.fillcolor('green')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    t.pu()
    t.goto(-200, 110)
    t.pd()
    t.fillcolor('orange')
    t.begin_fill()
    t.circle(40)
    t.end_fill()
    sleep(5)
    t.clear()

    #bandeira bahamas

def Bandeira11():
    t.pu()
    t.setheading(0)
    t.goto(0, 0)
    t.pd()
    t.fillcolor('blue')
    t.begin_fill()
    for _ in range(2):
        t.lt(90)
        t.fd(100)
        t.lt(90)
        t.fd(400)
    t.end_fill()
    t.fillcolor('yellow')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    t.fillcolor('blue')
    t.begin_fill()
    t.lt(90)
    t.fd(200)
    t.lt(90)
    t.fd(400)
    t.lt(90)
    t.fd(100)
    t.lt(90)
    t.fd(400)
    t.end_fill()
    t.lt(180)
    t.fd(400)
    t.rt(90)
    t.fd(100)
    t.fillcolor('black')
    t.begin_fill()
    t.rt(135)
    t.fd(212)
    t.rt(90)
    t.fd(212)
    t.lt(90)
    t.end_fill()
    sleep(5)
    t.clear()
    

    def Bandeira12():
        t.pu()
        t.goto(0, 0)
        t.setheading(0)
        t.pd()
        t.fillcolor('white')
        t.begin_fill()
        for _ in range(2):
            t.lt(90)
            t.fd(300)
            t.lt(90)
            t.fd(400)
        t.end_fill()
        t.fillcolor('red')
        t.begin_fill()
        t.pu()
        t.goto(-200, 100)
        t.pd()
        t.circle(55)
        t.end_fill()
        sleep(5)
        t.clear()
    Bandeira12()

    def Bandeira13():
     t.pu()
     t.goto(0, 0)
     t.pd()
     t.fillcolor('red')
     t.begin_fill()
     for _ in range(2):
        t.lt(90)
        t.fd(100)
        t.lt(90)
        t.fd(400)
     t.end_fill()
     t.fillcolor('green')
     t.begin_fill()
     t.lt(90)
     t.fd(200)
     t.lt(90)
     t.fd(400)
     t.lt(90)
     t.fd(100)
     t.lt(90)
     t.fd(400)
     t.end_fill()
     t.fillcolor('white')
     t.begin_fill()
     t.lt(90)
     t.fd(200)
     t.lt(90)
     t.fd(400)
     t.lt(90)
     t.fd(100)
     t.lt(90)
     t.fd(400)
     t.end_fill()
     sleep(5)
     t.clear()
    Bandeira13()

    


  




    



        
        
    
    


print(Bandeira0())    
print(BandeiraR())
print(Bandeira1())
print(Bandeira2())
print(Bandeira3())
print(Bandeira4())
print(Bandeira5())
print(Bandeira6())
print(Bandeira7())
print(Bandeira8())
print(Bandeira9())
print(Bandeira11())
print(Bandeira12())
print(Bandeira13())











mainloop()
